name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at every 12AM IST
     - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update WakaTime Status data
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: last_30_days
          COMMIT_MESSAGE: 🪄 Auto update README.md with Git hub profile WakaTime Status Data
