name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Status data
    runs-on: ubuntu-latest
    steps:
      - uses: dushyantDevTips/waka-readme-stats-1@resolve-spacing
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: '🪄 Auto Updates Readme file wakatime Status'
          SHOW_PROJECTS: false
          SHOW_LOC_CHART: false
          SHOW_PROFILE_VIEWS: false
