name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update WakaTime Status data
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: '🪄 Auto Updates Readme file wakatime Status'
          SHOW_PROFILE_VIEWS: false
          SHOW_UPDATED_DATE: false
          SHOW_PROJECTS: false
          SHOW_LOC_CHART: false
